In [2]:
import os   #used for directory work
import matplotlib.patches as mpatches #used for plot legends
import matplotlib.pyplot as plt   #used for creating plots
import pandas as pd
import numpy as np

In [11]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burn-0"
files = ["/TOA5_2879.ts_data.dat",\
             "/TOA5_4390.ts_data.dat","/TOA5_4975.ts_data.dat",\
             "/TOA5_4976.ts_data.dat","/TOA5_10442.ts_data.dat",\
             "/TOA5_11585.ts_data.dat"]
#files =["TOA5_4975.ts_data.dat","TOA5_2878.ts_data.dat","TOA5_4976.ts_data.dat","TOA5_11585.ts_data.dat","TOA5_2879.ts_data.dat"]
#df = pd.read_csv(path ,na_values = ['NAN',"00nan"],skiprows = 1)#, sep=",")

In [20]:
def file_to_df(path, file, f_skrow=4,h_skrow=1,raw=True):
    """
    This function takes in a path to a file then adds the correct headers 
    and makes the Timestamp the index and returns the dataframe
    
    inputs:
        path - directory of file
        file - wanted file to read in
        f_skrow - how many rows to skip for the data (default =  4)
        h_skrow - what row is the column names located
        raw - True if the timestamp is in the correct format
    output:
        df - pandas dataframe a usable format
    """    
    df = pd.read_csv(path+file, skiprows=f_skrow, na_values='NAN')
    headers_df = pd.read_csv(path+file,skiprows=h_skrow,nrows = 0)
    
    df.columns=list(headers_df)  #set the column names
    if raw:
        df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
    df.fillna(value=-9999, inplace=True)
    #df =df.set_index("TIMESTAMP")
    return(df)

In [13]:
#df = pd.read_csv(path+file, skiprows=f_skrow, na_values='NAN')
p = "/home/joey/Desktop/Data_Cleaning_Code/Burn-1/sonics/"
files =["A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1","C2",\
                   "C3","C4","D1","D2","D3","D4"]
for i in range(len(files)):
    df = pd.read_csv(p+files[i]+"_UVWT_Burn-1.txt",sep = " ")
    print(files[i])
    for j in range(len(df)):
        if df["DIAG"][j] != 0.0:
            print(df.iloc[j])

A1
A2
A3
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        15.0
Min       21.0
Sec       31.5
Name: 65399, dtype: float64
U         -0.45
V         -0.69
W          0.43
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        15.00
Min       26.00
Sec        7.80
Name: 68162, dtype: float64
A4
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         5.0
Hr        13.0
Min       39.0
Sec       40.6
Name: 4290, dtype: float64
B1
B2
B3
B4
C1
U         -0.32
V          0.09
W          0.32
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       49.00
Sec       19.00
Name: 46105, dtype: float64
C2
C3
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       16.0
Sec       50.9
Name: 26624, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       16.0
Sec       51.8
Name: 26633, dtype: float64
C4
D1
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       41.0
Sec       25.6
Name: 41371, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       48.0
Sec       53.1
Name: 45846, dtype: float64
D2
U           NaN
V         -1.08
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       41.00
Sec       39.40
Name: 41509, dtype: float64
D3
U           NaN
V          0.73
W           NaN
T          6.69
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       10.00
Sec       42.10
Name: 22936, dtype: float64
U           NaN
V         -0.23
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       12.00
Sec        4.10
Name: 23756, dtype: float64
U          NaN
V         -0.0
W          NaN
T          NaN
DIAG      82.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       21.0
Sec       20.8
Name: 29323, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       21.0
Sec       21.2
Name: 29327, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       23.0
Sec       30.7
Name: 30622, dtype: float64
U           NaN
V         -0.47
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       27.00
Sec       53.80
Name: 33253, dtype: float64
D4
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       10.0
Sec       17.3
Name: 22688, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       10.0
Sec       43.8
Name: 22953, dtype: float64
U           NaN
V         -0.58
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       10.00
Sec       49.30
Name: 23008, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       10.0
Sec       51.7
Name: 23032, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         5.0
Hr        14.0
Min       11.0
Sec        1.4
Name: 23129, dtype: float64
U           NaN
V         -0.47
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       11.00
Sec        6.50
Name: 23180, dtype: float64
U           NaN
V           NaN
W           NaN
T         16.53
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         5.00
Hr        14.00
Min       12.00
Sec        7.10
Name: 23786, dtype: float64

In [14]:
#df = pd.read_csv(path+file, skiprows=f_skrow, na_values='NAN')
p = "/home/joey/Desktop/Data_Cleaning_Code/Burn-2/sonics/"
files =["A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1","C2",\
                   "C3","C4","D1","D2","D3","D4"]
for i in range(len(files)):
    df = pd.read_csv(p+files[i]+"_UVWT_Burn-2.txt",sep = " ")
    print(files[i])
    for j in range(len(df)):
        if df["DIAG"][j] != 0.0:
            print(df.iloc[j])

A1
U         -2.30
V          1.67
W          2.11
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       35.00
Sec       13.70
Name: 18468, dtype: float64
U           NaN
V          1.59
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       35.00
Sec       16.90
Name: 18500, dtype: float64
U           NaN
V          0.24
W           NaN
T         17.33
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       35.00
Sec       17.00
Name: 18501, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       35.0
Sec       22.0
Name: 18551, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       35.0
Sec       43.6
Name: 18767, dtype: float64
A2
U           NaN
V           NaN
W           NaN
T          9.82
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       34.00
Sec       55.00
Name: 18281, dtype: float64
A3
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       26.9
Name: 0, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.0
Name: 1, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.1
Name: 2, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.2
Name: 3, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.3
Name: 4, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.4
Name: 5, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.5
Name: 6, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.6
Name: 7, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.7
Name: 8, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.8
Name: 9, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       27.9
Name: 10, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.0
Name: 11, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.1
Name: 12, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.2
Name: 13, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.3
Name: 14, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.4
Name: 15, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.5
Name: 16, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.6
Name: 17, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.7
Name: 18, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.8
Name: 19, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       28.9
Name: 20, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.0
Name: 21, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.1
Name: 22, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.2
Name: 23, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.3
Name: 24, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.4
Name: 25, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.5
Name: 26, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.6
Name: 27, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.7
Name: 28, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.8
Name: 29, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       29.9
Name: 30, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.0
Name: 31, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.1
Name: 32, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.2
Name: 33, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.3
Name: 34, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.4
Name: 35, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.5
Name: 36, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.6
Name: 37, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.7
Name: 38, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.8
Name: 39, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       30.9
Name: 40, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.0
Name: 41, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.1
Name: 42, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.2
Name: 43, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.3
Name: 44, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.4
Name: 45, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.5
Name: 46, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.6
Name: 47, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.7
Name: 48, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.8
Name: 49, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       31.9
Name: 50, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.0
Name: 51, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.1
Name: 52, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.2
Name: 53, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.3
Name: 54, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.4
Name: 55, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.5
Name: 56, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.6
Name: 57, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.7
Name: 58, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.8
Name: 59, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       32.9
Name: 60, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.0
Name: 61, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.1
Name: 62, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.2
Name: 63, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.3
Name: 64, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.4
Name: 65, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.5
Name: 66, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.6
Name: 67, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.7
Name: 68, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.8
Name: 69, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       33.9
Name: 70, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.0
Name: 71, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.1
Name: 72, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.2
Name: 73, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.3
Name: 74, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.4
Name: 75, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.5
Name: 76, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.6
Name: 77, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.7
Name: 78, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.8
Name: 79, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       34.9
Name: 80, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.0
Name: 81, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.1
Name: 82, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.2
Name: 83, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.3
Name: 84, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.4
Name: 85, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.5
Name: 86, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.6
Name: 87, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.7
Name: 88, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.8
Name: 89, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       35.9
Name: 90, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.0
Name: 91, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.1
Name: 92, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.2
Name: 93, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.3
Name: 94, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.4
Name: 95, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.5
Name: 96, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.6
Name: 97, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        4.0
Sec       36.7

U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.0
Name: 511, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.1
Name: 512, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.2
Name: 513, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.3
Name: 514, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.4
Name: 515, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.5
Name: 516, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.6
Name: 517, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.7
Name: 518, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.8
Name: 519, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       18.9
Name: 520, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.0
Name: 521, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.1
Name: 522, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.2
Name: 523, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.3
Name: 524, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.4
Name: 525, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.5
Name: 526, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.6
Name: 527, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.7
Name: 528, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.8
Name: 529, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       19.9
Name: 530, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.0
Name: 531, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.1
Name: 532, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.2
Name: 533, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.3
Name: 534, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.4
Name: 535, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.5
Name: 536, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.6
Name: 537, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.7
Name: 538, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.8
Name: 539, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       20.9
Name: 540, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.0
Name: 541, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.1
Name: 542, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.2
Name: 543, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.3
Name: 544, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.4
Name: 545, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.5
Name: 546, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.6
Name: 547, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.7
Name: 548, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.8
Name: 549, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       21.9
Name: 550, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.0
Name: 551, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.1
Name: 552, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.2
Name: 553, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.3
Name: 554, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.4
Name: 555, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.5
Name: 556, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.6
Name: 557, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.7
Name: 558, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.8
Name: 559, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       22.9
Name: 560, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.0
Name: 561, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.1
Name: 562, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.2
Name: 563, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.3
Name: 564, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.4
Name: 565, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.5
Name: 566, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.6
Name: 567, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.7
Name: 568, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.8
Name: 569, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       23.9
Name: 570, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.0
Name: 571, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.1
Name: 572, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.2
Name: 573, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.3
Name: 574, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.4
Name: 575, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.5
Name: 576, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.6
Name: 577, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.7
Name: 578, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.8
Name: 579, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       24.9
Name: 580, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.0
Name: 581, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.1
Name: 582, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.2
Name: 583, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.3
Name: 584, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.4
Name: 585, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.5
Name: 586, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.6
Name: 587, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.7
Name: 588, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.8
Name: 589, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       25.9
Name: 590, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.0
Name: 591, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.1
Name: 592, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.2
Name: 593, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.3
Name: 594, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.4
Name: 595, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.5
Name: 596, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.6
Name: 597, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.7
Name: 598, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.8
Name: 599, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       26.9
Name: 600, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.0
Name: 601, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.1
Name: 602, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.2
Name: 603, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.3
Name: 604, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.4
Name: 605, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.5
Name: 606, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.6
Name: 607, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.7
Name: 608, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.8
Name: 609, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       27.9
Name: 610, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       28.0
Name: 611, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       28.1
Name: 612, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       28.2
Name: 613, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       28.3
Name: 614, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0

Name: 919, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       58.9
Name: 920, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.0
Name: 921, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.1
Name: 922, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.2
Name: 923, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.3
Name: 924, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.4
Name: 925, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.5
Name: 926, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.6
Name: 927, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.7
Name: 928, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.8
Name: 929, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        5.0
Sec       59.9
Name: 930, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.0
Name: 931, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.1
Name: 932, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.2
Name: 933, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.3
Name: 934, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.4
Name: 935, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.5
Name: 936, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.6
Name: 937, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.7
Name: 938, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.8
Name: 939, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        0.9
Name: 940, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.0
Name: 941, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.1
Name: 942, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.2
Name: 943, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.3
Name: 944, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.4
Name: 945, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.5
Name: 946, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.6
Name: 947, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.7
Name: 948, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.8
Name: 949, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        1.9
Name: 950, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.0
Name: 951, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.1
Name: 952, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.2
Name: 953, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.3
Name: 954, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.4
Name: 955, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.5
Name: 956, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.6
Name: 957, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.7
Name: 958, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.8
Name: 959, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        2.9
Name: 960, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.0
Name: 961, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.1
Name: 962, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.2
Name: 963, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.3
Name: 964, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.4
Name: 965, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.5
Name: 966, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.6
Name: 967, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.7
Name: 968, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.8
Name: 969, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        3.9
Name: 970, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.0
Name: 971, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.1
Name: 972, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.2
Name: 973, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.3
Name: 974, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.4
Name: 975, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.5
Name: 976, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.6
Name: 977, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.7
Name: 978, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.8
Name: 979, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        4.9
Name: 980, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.0
Name: 981, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.1
Name: 982, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.2
Name: 983, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.3
Name: 984, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.4
Name: 985, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.5
Name: 986, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.6
Name: 987, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.7
Name: 988, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.8
Name: 989, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        5.9
Name: 990, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.0
Name: 991, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.1
Name: 992, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.2
Name: 993, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.3
Name: 994, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.4
Name: 995, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.5
Name: 996, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.6
Name: 997, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.7
Name: 998, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.8
Name: 999, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        6.9
Name: 1000, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.0
Name: 1001, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.1
Name: 1002, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.2
Name: 1003, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.3
Name: 1004, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.4
Name: 1005, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.5
Name: 1006, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.6
Name: 1007, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.7
Name: 1008, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.8
Name: 1009, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        7.9
Name: 1010, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.0
Name: 1011, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.1
Name: 1012, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.2
Name: 1013, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.3
Name: 1014, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.4
Name: 1015, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.5
Name: 1016, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.6
Name: 1017, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.7
Name: 1018, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.8
Name: 1019, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        8.9
Name: 1020, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        9.0
Name: 1021, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        9.1
Name: 1022, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec        9.2
Name: 1023, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN

Name: 1291, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.1
Name: 1292, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.2
Name: 1293, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.3
Name: 1294, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.4
Name: 1295, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.5
Name: 1296, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.6
Name: 1297, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.7
Name: 1298, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.8
Name: 1299, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       36.9
Name: 1300, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.0
Name: 1301, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.1
Name: 1302, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.2
Name: 1303, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.3
Name: 1304, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.4
Name: 1305, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.5
Name: 1306, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.6
Name: 1307, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.7
Name: 1308, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.8
Name: 1309, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       37.9
Name: 1310, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.0
Name: 1311, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.1
Name: 1312, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.2
Name: 1313, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.3
Name: 1314, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.4
Name: 1315, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.5
Name: 1316, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.6
Name: 1317, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.7
Name: 1318, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.8
Name: 1319, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       38.9
Name: 1320, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.0
Name: 1321, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.1
Name: 1322, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.2
Name: 1323, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.3
Name: 1324, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.4
Name: 1325, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.5
Name: 1326, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.6
Name: 1327, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.7
Name: 1328, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.8
Name: 1329, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       39.9
Name: 1330, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.0
Name: 1331, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.1
Name: 1332, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.2
Name: 1333, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.3
Name: 1334, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.4
Name: 1335, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.5
Name: 1336, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.6
Name: 1337, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.7
Name: 1338, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.8
Name: 1339, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       40.9
Name: 1340, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.0
Name: 1341, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.1
Name: 1342, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.2
Name: 1343, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.3
Name: 1344, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.4
Name: 1345, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.5
Name: 1346, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.6
Name: 1347, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.7
Name: 1348, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.8
Name: 1349, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       41.9
Name: 1350, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.0
Name: 1351, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.1
Name: 1352, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.2
Name: 1353, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.3
Name: 1354, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.4
Name: 1355, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.5
Name: 1356, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.6
Name: 1357, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.7
Name: 1358, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.8
Name: 1359, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       42.9
Name: 1360, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.0
Name: 1361, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.1
Name: 1362, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.2
Name: 1363, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.3
Name: 1364, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.4
Name: 1365, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.5
Name: 1366, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.6
Name: 1367, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.7
Name: 1368, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.8
Name: 1369, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       43.9
Name: 1370, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.0
Name: 1371, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.1
Name: 1372, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.2
Name: 1373, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.3
Name: 1374, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.4
Name: 1375, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.5
Name: 1376, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.6
Name: 1377, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.7
Name: 1378, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.8
Name: 1379, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       44.9
Name: 1380, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.0
Name: 1381, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.1
Name: 1382, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.2
Name: 1383, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.3
Name: 1384, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.4
Name: 1385, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.5
Name: 1386, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.6
Name: 1387, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.7
Name: 1388, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.8
Name: 1389, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       45.9
Name: 1390, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       46.0
Name: 1391, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       46.1
Name: 1392, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       46.2
Name: 1393, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       46.3
Name: 1394, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        6.0
Sec       46.4
Name: 1395, dtype: float64

Name: 1641, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.1
Name: 1642, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.2
Name: 1643, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.3
Name: 1644, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.4
Name: 1645, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.5
Name: 1646, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.6
Name: 1647, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.7
Name: 1648, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.8
Name: 1649, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       11.9
Name: 1650, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.0
Name: 1651, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.1
Name: 1652, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.2
Name: 1653, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.3
Name: 1654, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.4
Name: 1655, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.5
Name: 1656, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.6
Name: 1657, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.7
Name: 1658, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.8
Name: 1659, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       12.9
Name: 1660, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.0
Name: 1661, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.1
Name: 1662, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.2
Name: 1663, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.3
Name: 1664, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.4
Name: 1665, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.5
Name: 1666, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.6
Name: 1667, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.7
Name: 1668, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.8
Name: 1669, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       13.9
Name: 1670, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.0
Name: 1671, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.1
Name: 1672, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.2
Name: 1673, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.3
Name: 1674, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.4
Name: 1675, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.5
Name: 1676, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.6
Name: 1677, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.7
Name: 1678, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.8
Name: 1679, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       14.9
Name: 1680, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.0
Name: 1681, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.1
Name: 1682, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.2
Name: 1683, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.3
Name: 1684, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.4
Name: 1685, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.5
Name: 1686, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.6
Name: 1687, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.7
Name: 1688, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.8
Name: 1689, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       15.9
Name: 1690, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.0
Name: 1691, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.1
Name: 1692, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.2
Name: 1693, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.3
Name: 1694, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.4
Name: 1695, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.5
Name: 1696, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.6
Name: 1697, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.7
Name: 1698, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.8
Name: 1699, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       16.9
Name: 1700, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.0
Name: 1701, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.1
Name: 1702, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.2
Name: 1703, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.3
Name: 1704, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.4
Name: 1705, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.5
Name: 1706, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.6
Name: 1707, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.7
Name: 1708, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.8
Name: 1709, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       17.9
Name: 1710, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.0
Name: 1711, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.1
Name: 1712, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.2
Name: 1713, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.3
Name: 1714, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.4
Name: 1715, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.5
Name: 1716, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.6
Name: 1717, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.7
Name: 1718, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.8
Name: 1719, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       18.9
Name: 1720, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.0
Name: 1721, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.1
Name: 1722, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.2
Name: 1723, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.3
Name: 1724, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.4
Name: 1725, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.5
Name: 1726, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.6
Name: 1727, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.7
Name: 1728, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.8
Name: 1729, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       19.9
Name: 1730, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.0
Name: 1731, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.1
Name: 1732, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.2
Name: 1733, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.3
Name: 1734, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.4
Name: 1735, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.5
Name: 1736, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.6
Name: 1737, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.7
Name: 1738, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.8
Name: 1739, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       20.9
Name: 1740, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       21.0
Name: 1741, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       21.1
Name: 1742, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       21.2
Name: 1743, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       21.3
Name: 1744, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       21.4
Name: 1745, dtype: float64

Name: 2049, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       51.9
Name: 2050, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.0
Name: 2051, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.1
Name: 2052, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.2
Name: 2053, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.3
Name: 2054, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.4
Name: 2055, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.5
Name: 2056, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.6
Name: 2057, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.7
Name: 2058, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.8
Name: 2059, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       52.9
Name: 2060, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.0
Name: 2061, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.1
Name: 2062, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.2
Name: 2063, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.3
Name: 2064, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.4
Name: 2065, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.5
Name: 2066, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.6
Name: 2067, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.7
Name: 2068, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.8
Name: 2069, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       53.9
Name: 2070, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.0
Name: 2071, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.1
Name: 2072, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.2
Name: 2073, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.3
Name: 2074, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.4
Name: 2075, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.5
Name: 2076, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.6
Name: 2077, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.7
Name: 2078, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.8
Name: 2079, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       54.9
Name: 2080, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.0
Name: 2081, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.1
Name: 2082, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.2
Name: 2083, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.3
Name: 2084, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.4
Name: 2085, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.5
Name: 2086, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.6
Name: 2087, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.7
Name: 2088, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.8
Name: 2089, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       55.9
Name: 2090, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.0
Name: 2091, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.1
Name: 2092, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.2
Name: 2093, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.3
Name: 2094, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.4
Name: 2095, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.5
Name: 2096, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.6
Name: 2097, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.7
Name: 2098, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.8
Name: 2099, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       56.9
Name: 2100, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.0
Name: 2101, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.1
Name: 2102, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.2
Name: 2103, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.3
Name: 2104, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.4
Name: 2105, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.5
Name: 2106, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.6
Name: 2107, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.7
Name: 2108, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.8
Name: 2109, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       57.9
Name: 2110, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.0
Name: 2111, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.1
Name: 2112, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.2
Name: 2113, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.3
Name: 2114, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.4
Name: 2115, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.5
Name: 2116, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.6
Name: 2117, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.7
Name: 2118, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.8
Name: 2119, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       58.9
Name: 2120, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.0
Name: 2121, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.1
Name: 2122, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.2
Name: 2123, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.3
Name: 2124, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.4
Name: 2125, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.5
Name: 2126, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.6
Name: 2127, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.7
Name: 2128, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.8
Name: 2129, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        7.0
Sec       59.9
Name: 2130, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.0
Name: 2131, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.1
Name: 2132, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.2
Name: 2133, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.3
Name: 2134, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.4
Name: 2135, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.5
Name: 2136, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.6
Name: 2137, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.7
Name: 2138, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.8
Name: 2139, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        0.9
Name: 2140, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.0
Name: 2141, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.1
Name: 2142, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.2
Name: 2143, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.3
Name: 2144, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.4
Name: 2145, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.5
Name: 2146, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.6
Name: 2147, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.7
Name: 2148, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.8
Name: 2149, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        1.9
Name: 2150, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        2.0
Name: 2151, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        2.1
Name: 2152, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec        2.2
Name: 2153, dtype: float64

Name: 2671, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.1
Name: 2672, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.2
Name: 2673, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.3
Name: 2674, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.4
Name: 2675, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.5
Name: 2676, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.6
Name: 2677, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.7
Name: 2678, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.8
Name: 2679, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       54.9
Name: 2680, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.0
Name: 2681, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.1
Name: 2682, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.2
Name: 2683, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.3
Name: 2684, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.4
Name: 2685, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.5
Name: 2686, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.6
Name: 2687, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.7
Name: 2688, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.8
Name: 2689, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       55.9
Name: 2690, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.0
Name: 2691, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.1
Name: 2692, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.2
Name: 2693, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.3
Name: 2694, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.4
Name: 2695, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.5
Name: 2696, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.6
Name: 2697, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.7
Name: 2698, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.8
Name: 2699, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       56.9
Name: 2700, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.0
Name: 2701, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.1
Name: 2702, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.2
Name: 2703, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.3
Name: 2704, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.4
Name: 2705, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.5
Name: 2706, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.6
Name: 2707, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.7
Name: 2708, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.8
Name: 2709, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       57.9
Name: 2710, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.0
Name: 2711, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.1
Name: 2712, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.2
Name: 2713, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.3
Name: 2714, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.4
Name: 2715, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.5
Name: 2716, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.6
Name: 2717, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.7
Name: 2718, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.8
Name: 2719, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       58.9
Name: 2720, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.0
Name: 2721, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.1
Name: 2722, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.2
Name: 2723, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.3
Name: 2724, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.4
Name: 2725, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.5
Name: 2726, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.6
Name: 2727, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.7
Name: 2728, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.8
Name: 2729, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        8.0
Sec       59.9
Name: 2730, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.0
Name: 2731, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.1
Name: 2732, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.2
Name: 2733, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.3
Name: 2734, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.4
Name: 2735, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.5
Name: 2736, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.6
Name: 2737, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.7
Name: 2738, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.8
Name: 2739, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        0.9
Name: 2740, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.0
Name: 2741, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.1
Name: 2742, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.2
Name: 2743, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.3
Name: 2744, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.4
Name: 2745, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.5
Name: 2746, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.6
Name: 2747, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.7
Name: 2748, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.8
Name: 2749, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        1.9
Name: 2750, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.0
Name: 2751, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.1
Name: 2752, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.2
Name: 2753, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.3
Name: 2754, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.4
Name: 2755, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.5
Name: 2756, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.6
Name: 2757, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.7
Name: 2758, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.8
Name: 2759, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        2.9
Name: 2760, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.0
Name: 2761, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.1
Name: 2762, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.2
Name: 2763, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.3
Name: 2764, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.4
Name: 2765, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.5
Name: 2766, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.6
Name: 2767, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.7
Name: 2768, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.8
Name: 2769, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        3.9
Name: 2770, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        4.0
Name: 2771, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        4.1
Name: 2772, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        4.2
Name: 2773, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        4.3
Name: 2774, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec        4.4
Name: 2775, dtype: float64

Name: 3129, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       39.9
Name: 3130, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.0
Name: 3131, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.1
Name: 3132, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.2
Name: 3133, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.3
Name: 3134, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.4
Name: 3135, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.5
Name: 3136, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.6
Name: 3137, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.7
Name: 3138, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.8
Name: 3139, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       40.9
Name: 3140, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.0
Name: 3141, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.1
Name: 3142, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.2
Name: 3143, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.3
Name: 3144, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.4
Name: 3145, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.5
Name: 3146, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.6
Name: 3147, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.7
Name: 3148, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.8
Name: 3149, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       41.9
Name: 3150, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.0
Name: 3151, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.1
Name: 3152, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.2
Name: 3153, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.3
Name: 3154, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.4
Name: 3155, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.5
Name: 3156, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.6
Name: 3157, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.7
Name: 3158, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.8
Name: 3159, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       42.9
Name: 3160, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.0
Name: 3161, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.1
Name: 3162, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.2
Name: 3163, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.3
Name: 3164, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.4
Name: 3165, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.5
Name: 3166, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.6
Name: 3167, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.7
Name: 3168, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.8
Name: 3169, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       43.9
Name: 3170, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.0
Name: 3171, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.1
Name: 3172, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.2
Name: 3173, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.3
Name: 3174, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.4
Name: 3175, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.5
Name: 3176, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.6
Name: 3177, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.7
Name: 3178, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.8
Name: 3179, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       44.9
Name: 3180, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.0
Name: 3181, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.1
Name: 3182, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.2
Name: 3183, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.3
Name: 3184, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.4
Name: 3185, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.5
Name: 3186, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.6
Name: 3187, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.7
Name: 3188, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.8
Name: 3189, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       45.9
Name: 3190, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.0
Name: 3191, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.1
Name: 3192, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.2
Name: 3193, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.3
Name: 3194, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.4
Name: 3195, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.5
Name: 3196, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.6
Name: 3197, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.7
Name: 3198, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.8
Name: 3199, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       46.9
Name: 3200, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.0
Name: 3201, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.1
Name: 3202, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.2
Name: 3203, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.3
Name: 3204, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.4
Name: 3205, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.5
Name: 3206, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.6
Name: 3207, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.7
Name: 3208, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.8
Name: 3209, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       47.9
Name: 3210, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.0
Name: 3211, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.1
Name: 3212, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.2
Name: 3213, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.3
Name: 3214, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.4
Name: 3215, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.5
Name: 3216, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.6
Name: 3217, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.7
Name: 3218, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.8
Name: 3219, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       48.9
Name: 3220, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.0
Name: 3221, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.1
Name: 3222, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.2
Name: 3223, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.3
Name: 3224, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.4
Name: 3225, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.5
Name: 3226, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.6
Name: 3227, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.7
Name: 3228, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.8
Name: 3229, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       49.9
Name: 3230, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       50.0
Name: 3231, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       50.1
Name: 3232, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min        9.0
Sec       50.2
Name: 3233, dtype: float64

Name: 3601, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.1
Name: 3602, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.2
Name: 3603, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.3
Name: 3604, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.4
Name: 3605, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.5
Name: 3606, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.6
Name: 3607, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.7
Name: 3608, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.8
Name: 3609, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       27.9
Name: 3610, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.0
Name: 3611, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.1
Name: 3612, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.2
Name: 3613, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.3
Name: 3614, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.4
Name: 3615, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.5
Name: 3616, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.6
Name: 3617, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.7
Name: 3618, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.8
Name: 3619, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       28.9
Name: 3620, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.0
Name: 3621, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.1
Name: 3622, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.2
Name: 3623, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.3
Name: 3624, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.4
Name: 3625, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.5
Name: 3626, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.6
Name: 3627, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.7
Name: 3628, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.8
Name: 3629, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       29.9
Name: 3630, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.0
Name: 3631, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.1
Name: 3632, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.2
Name: 3633, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.3
Name: 3634, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.4
Name: 3635, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.5
Name: 3636, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.6
Name: 3637, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.7
Name: 3638, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.8
Name: 3639, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       30.9
Name: 3640, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.0
Name: 3641, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.1
Name: 3642, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.2
Name: 3643, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.3
Name: 3644, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.4
Name: 3645, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.5
Name: 3646, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.6
Name: 3647, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.7
Name: 3648, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.8
Name: 3649, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       31.9
Name: 3650, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.0
Name: 3651, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.1
Name: 3652, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.2
Name: 3653, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.3
Name: 3654, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.4
Name: 3655, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.5
Name: 3656, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.6
Name: 3657, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.7
Name: 3658, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.8
Name: 3659, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       32.9
Name: 3660, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.0
Name: 3661, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.1
Name: 3662, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.2
Name: 3663, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.3
Name: 3664, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.4
Name: 3665, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.5
Name: 3666, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.6
Name: 3667, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.7
Name: 3668, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.8
Name: 3669, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       33.9
Name: 3670, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.0
Name: 3671, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.1
Name: 3672, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.2
Name: 3673, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.3
Name: 3674, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.4
Name: 3675, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.5
Name: 3676, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.6
Name: 3677, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.7
Name: 3678, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.8
Name: 3679, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       34.9
Name: 3680, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.0
Name: 3681, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.1
Name: 3682, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.2
Name: 3683, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.3
Name: 3684, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.4
Name: 3685, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.5
Name: 3686, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.6
Name: 3687, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.7
Name: 3688, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.8
Name: 3689, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       35.9
Name: 3690, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.0
Name: 3691, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.1
Name: 3692, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.2
Name: 3693, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.3
Name: 3694, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.4
Name: 3695, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.5
Name: 3696, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.6
Name: 3697, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.7
Name: 3698, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.8
Name: 3699, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       36.9
Name: 3700, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       37.0
Name: 3701, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       37.1
Name: 3702, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       37.2
Name: 3703, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       37.3
Name: 3704, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       10.0
Sec       37.4
Name: 3705, dtype: float64

A4
B1
U           NaN
V         -0.75
W           NaN
T         16.95
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       36.00
Sec       25.20
Name: 19183, dtype: float64
U           NaN
V           NaN
W           NaN
T        242.96
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       36.00
Sec       25.30
Name: 19184, dtype: float64
B2
U           NaN
V           NaN
W           NaN
T         12.46
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       34.00
Sec       35.60
Name: 18087, dtype: float64
B3
B4
C1
U           NaN
V         -0.48
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       35.00
Sec       34.50
Name: 18676, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       35.0
Sec       57.4
Name: 18905, dtype: float64
U          NaN
V         -0.0
W          NaN
T          NaN
DIAG      82.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       36.0
Sec       46.1
Name: 19392, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       37.0
Sec        6.1
Name: 19592, dtype: float64
U         -0.43
V         -1.40
W          0.94
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       37.00
Sec       10.40
Name: 19635, dtype: float64
U           NaN
V           NaN
W           NaN
T          7.08
DIAG      22.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       37.00
Sec       12.00
Name: 19651, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       37.0
Sec       13.7
Name: 19668, dtype: float64
U           NaN
V           NaN
W           NaN
T         23.89
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       37.00
Sec       13.80
Name: 19669, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       37.0
Sec       13.9
Name: 19670, dtype: float64
U           NaN
V         -0.59
W           NaN
T         16.01
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       37.00
Sec       37.80
Name: 19909, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       37.0
Sec       39.3
Name: 19924, dtype: float64
U           NaN
V           NaN
W           NaN
T          6.13
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       37.00
Sec       40.60
Name: 19937, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      52.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       37.0
Sec       46.0
Name: 19991, dtype: float64
U           NaN
V           NaN
W           NaN
T        267.99
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       38.00
Sec       43.30
Name: 20564, dtype: float64
C2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       35.0
Sec       54.9
Name: 18880, dtype: float64
U           NaN
V           NaN
W           NaN
T          6.24
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       35.00
Sec       55.00
Name: 18881, dtype: float64
U           NaN
V           NaN
W           NaN
T          8.18
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       36.00
Sec        8.80
Name: 19019, dtype: float64
C3
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       34.0
Sec        2.1
Name: 17752, dtype: float64
U           NaN
V           NaN
W           NaN
T         11.36
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       34.00
Sec       20.00
Name: 17931, dtype: float64
C4
D1
U           NaN
V           NaN
W           NaN
T          9.35
DIAG      22.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       37.00
Sec        6.10
Name: 19592, dtype: float64
U         -0.65
V          0.56
W          0.12
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       37.00
Sec       47.80
Name: 20009, dtype: float64
D2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       35.0
Sec       35.5
Name: 18686, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       35.0
Sec       52.3
Name: 18854, dtype: float64
U         -0.39
V         -0.98
W          0.62
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       35.00
Sec       53.10
Name: 18862, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       35.0
Sec       53.3
Name: 18864, dtype: float64
U           NaN
V           NaN
W         -7.83
T           NaN
DIAG      86.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       36.00
Sec       40.00
Name: 19331, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        11.0
Min       36.0
Sec       40.5
Name: 19336, dtype: float64
U         -2.39
V         -0.68
W         -0.76
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       36.00
Sec       46.40
Name: 19395, dtype: float64
U           NaN
V           NaN
W           NaN
T          6.17
DIAG      22.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       36.00
Sec       48.40
Name: 19415, dtype: float64
D3
D4
U           NaN
V         -0.21
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        11.00
Min       31.00
Sec       36.20
Name: 16293, dtype: float64

In [15]:
#df = pd.read_csv(path+file, skiprows=f_skrow, na_values='NAN')
p = "/home/joey/Desktop/Data_Cleaning_Code/Burn-3/sonics/"
files =["A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1","C2",\
                   "C3","C4","D1","D2","D3","D4"]
for i in range(len(files)):
    df = pd.read_csv(p+files[i]+"_UVWT_Burn-3.txt",sep = " ")
    print(files[i])
    for j in range(len(df)):
        if df["DIAG"][j] != 0.0:
            print(df.iloc[j])

A1
U         -1.36
V          1.04
W          1.26
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       37.00
Sec       47.80
Name: 26369, dtype: float64
U           NaN
V         -0.25
W           NaN
T         44.69
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       37.00
Sec       59.30
Name: 26484, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec        0.5
Name: 26496, dtype: float64
U           NaN
V         -0.50
W           NaN
T          9.05
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec        6.10
Name: 26552, dtype: float64
U           NaN
V          0.59
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec        8.00
Name: 26571, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       11.9
Name: 26610, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       12.1
Name: 26612, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       15.5
Name: 26646, dtype: float64
U           NaN
V          2.27
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       16.10
Name: 26652, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       33.9
Name: 26830, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       46.9
Name: 26960, dtype: float64
U           NaN
V         -0.61
W           NaN
T         21.84
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       47.00
Name: 26961, dtype: float64
U           NaN
V          1.70
W           NaN
T         26.28
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       47.10
Name: 26962, dtype: float64
U           NaN
V           NaN
W           NaN
T         30.32
DIAG      22.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       47.30
Name: 26964, dtype: float64
U           NaN
V           NaN
W           NaN
T         18.41
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       47.40
Name: 26965, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       52.0
Name: 27011, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       53.1
Name: 27022, dtype: float64
U           NaN
V           NaN
W           NaN
T         48.62
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       53.80
Name: 27029, dtype: float64
U          NaN
V          NaN
W          NaN
T         36.3
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       57.3
Name: 27064, dtype: float64
U           NaN
V           NaN
W           NaN
T         73.26
DIAG      22.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       58.40
Name: 27075, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       59.8
Name: 27089, dtype: float64
U          0.12
V          0.37
W         -0.13
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       39.00
Sec       21.60
Name: 27307, dtype: float64
U         -0.17
V         -0.09
W          0.18
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       39.00
Sec       25.30
Name: 27344, dtype: float64
A2
U           NaN
V          2.34
W           NaN
T         11.49
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       37.00
Sec       17.00
Name: 26061, dtype: float64
A3
A4
B1
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      46.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       21.0
Name: 26701, dtype: float64
U           NaN
V           NaN
W         -6.19
T           NaN
DIAG      92.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       21.10
Name: 26702, dtype: float64
U          0.69
V          2.53
W         -0.89
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       22.70
Name: 26718, dtype: float64
U           NaN
V          2.14
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       38.00
Sec       58.60
Name: 27077, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       58.7
Name: 27078, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       38.0
Sec       59.1
Name: 27082, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       39.0
Sec        2.8
Name: 27119, dtype: float64
U         -0.73
V         -0.17
W         -0.26
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       39.00
Sec        3.70
Name: 27128, dtype: float64
U           NaN
V         -1.45
W           NaN
T        281.67
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       39.00
Sec        3.80
Name: 27129, dtype: float64
U           NaN
V           NaN
W           NaN
T         28.55
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       39.00
Sec        4.50
Name: 27136, dtype: float64
B2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       34.0
Sec       16.0
Name: 24251, dtype: float64
U         -0.65
V          0.15
W         -0.45
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       34.00
Sec       40.60
Name: 24497, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       39.0
Sec       10.7
Name: 27198, dtype: float64
U           NaN
V           NaN
W           NaN
T         13.43
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       39.00
Sec       11.90
Name: 27210, dtype: float64
U           NaN
V           NaN
W           NaN
T         14.14
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       39.00
Sec       12.00
Name: 27211, dtype: float64
B3
B4
C1
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       31.0
Sec       48.0
Name: 22771, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       32.0
Sec       57.5
Name: 23466, dtype: float64

C2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       30.0
Sec       42.2
Name: 22113, dtype: float64
U         -0.75
V         -0.03
W         -0.32
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       31.00
Sec        7.20
Name: 22363, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       31.0
Sec       58.7
Name: 22878, dtype: float64
U           NaN
V         -0.23
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       31.00
Sec       59.30
Name: 22884, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       32.0
Sec       11.4
Name: 23005, dtype: float64
U         -0.08
V         -0.66
W          0.48
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec       13.20
Name: 23023, dtype: float64
U           NaN
V          1.62
W           NaN
T        244.99
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec       13.40
Name: 23025, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       32.0
Sec       14.6
Name: 23037, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       32.0
Sec       33.8
Name: 23229, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       32.0
Sec       33.9
Name: 23230, dtype: float64
U         -1.15
V         -0.73
W         -0.02
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec       34.00
Name: 23231, dtype: float64
U           NaN
V          2.27
W           NaN
T          8.22
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       33.00
Sec        0.10
Name: 23492, dtype: float64
C3
U           NaN
V          0.81
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       29.00
Sec       27.40
Name: 21365, dtype: float64
U           NaN
V          0.51
W           NaN
T         12.12
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       29.00
Sec       28.40
Name: 21375, dtype: float64
U           NaN
V           NaN
W           NaN
T         25.23
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       29.00
Sec       34.00
Name: 21431, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       35.3
Name: 21444, dtype: float64
U           NaN
V         -2.77
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       29.00
Sec       35.60
Name: 21447, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       36.6
Name: 21457, dtype: float64
U          NaN
V          NaN
W          NaN
T          9.5
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       38.3
Name: 21474, dtype: float64
U           NaN
V           NaN
W         -4.06
T           NaN
DIAG      92.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       29.00
Sec       41.90
Name: 21510, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       48.6
Name: 21577, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       52.6
Name: 21617, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       30.0
Sec       40.1
Name: 22092, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       30.0
Sec       42.5
Name: 22116, dtype: float64
C4
D1
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       31.0
Sec       49.8
Name: 22789, dtype: float64
U           NaN
V         -1.56
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec        4.50
Name: 22936, dtype: float64
D2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       28.0
Sec       38.7
Name: 20878, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       31.0
Sec       49.9
Name: 22790, dtype: float64
U           NaN
V          1.12
W           NaN
T        250.53
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec       13.30
Name: 23024, dtype: float64
U           NaN
V         -0.46
W           NaN
T        236.11
DIAG      82.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec       15.10
Name: 23042, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       32.0
Sec       15.2
Name: 23043, dtype: float64
U           NaN
V           NaN
W           NaN
T         18.11
DIAG       6.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec       16.70
Name: 23058, dtype: float64
U           NaN
V          2.02
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       32.00
Sec       20.10
Name: 23092, dtype: float64
D3
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       10.7
Name: 21198, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       52.6
Name: 21617, dtype: float64
U           NaN
V           NaN
W           NaN
T         12.28
DIAG      12.00
YYYY    2018.00
MM         3.00
DD         6.00
Hr        13.00
Min       29.00
Sec       52.80
Name: 21619, dtype: float64
U          NaN
V         -0.5
W          NaN
T         15.5
DIAG      82.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       29.0
Sec       55.2
Name: 21643, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       30.0
Sec        1.2
Name: 21703, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD         6.0
Hr        13.0
Min       30.0
Sec       12.7
Name: 21818, dtype: float64
D4

In [16]:
#df = pd.read_csv(path+file, skiprows=f_skrow, na_values='NAN')
p = "/home/joey/Desktop/Data_Cleaning_Code/Burn-4/sonics/"
files =["A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1","C2",\
                   "C3","C4","D1","D2","D3","D4"]
for i in range(len(files)):
    df = pd.read_csv(p+files[i]+"_UVWT_Burn-4.txt",sep = " ")
    print(files[i])
    for j in range(len(df)):
        if df["DIAG"][j] != 0.0:
            print(df.iloc[j])

A1
A2
A3
A4
B1
B2
U           NaN
V          1.85
W           NaN
T          6.10
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        10.00
Min       54.00
Sec       37.00
Name: 35667, dtype: float64
B3
B4
C1
C2
U           NaN
V          1.53
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        11.00
Min        0.00
Sec       10.80
Name: 39005, dtype: float64
C3
C4
D1
D2
U           NaN
V         -0.22
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        10.00
Min       55.00
Sec       23.30
Name: 36130, dtype: float64
D3
U          1.50
V         -0.11
W          0.83
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        11.00
Min        2.00
Sec       39.00
Name: 40487, dtype: float64
U         38.26
V           NaN
W           NaN
T          5.04
DIAG      26.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        11.00
Min        4.00
Sec       23.20
Name: 41529, dtype: float64
D4
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        11.0
Min        2.0
Sec       42.3
Name: 40520, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        11.0
Min        2.0
Sec       43.2
Name: 40529, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        11.0
Min        4.0
Sec       14.0
Name: 41437, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        11.0
Min        6.0
Sec       26.4
Name: 42761, dtype: float64

In [17]:
#df = pd.read_csv(path+file, skiprows=f_skrow, na_values='NAN')
p = "/home/joey/Desktop/Data_Cleaning_Code/Burn-5/sonics/"
files =["A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1","C2",\
                   "C3","C4","D1","D2","D3","D4"]
for i in range(len(files)):
    df = pd.read_csv(p+files[i]+"_UVWT_Burn-5.txt",sep = " ")
    print(files[i])
    for j in range(len(df)):
        if df["DIAG"][j] != 0.0:
            print(df.iloc[j])

A1
A2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       44.0
Sec       11.9
Name: 16935, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       44.0
Sec       12.4
Name: 16940, dtype: float64
U           NaN
V          3.03
W           NaN
T           NaN
DIAG      16.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       44.00
Sec       24.00
Name: 17056, dtype: float64
A3
U           NaN
V          0.47
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       44.00
Sec       33.70
Name: 17153, dtype: float64
U           NaN
V           NaN
W           NaN
T          5.59
DIAG      22.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       44.00
Sec       43.20
Name: 17248, dtype: float64
U           NaN
V          3.08
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       44.00
Sec       56.20
Name: 17378, dtype: float64
U           NaN
V          1.73
W           NaN
T         25.04
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       17.50
Name: 17591, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       26.1
Name: 17677, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       26.3
Name: 17679, dtype: float64
U           NaN
V          0.64
W           NaN
T         34.83
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       30.50
Name: 17721, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       32.0
Name: 17736, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       34.4
Name: 17760, dtype: float64
U           NaN
V          2.17
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       34.50
Name: 17761, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       36.3
Name: 17779, dtype: float64
U           NaN
V           NaN
W           NaN
T          5.66
DIAG      12.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       38.90
Name: 17805, dtype: float64
U           NaN
V          1.26
W           NaN
T         63.38
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       49.40
Name: 17910, dtype: float64
U           NaN
V           NaN
W         -2.59
T           NaN
DIAG      62.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       49.50
Name: 17911, dtype: float64
U           NaN
V          0.60
W           NaN
T         15.99
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       50.50
Name: 17921, dtype: float64
U           NaN
V          2.75
W           NaN
T          3.55
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       52.10
Name: 17937, dtype: float64
U          NaN
V          NaN
W          NaN
T        262.0
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       52.2
Name: 17938, dtype: float64
U           NaN
V           NaN
W           NaN
T         25.99
DIAG      12.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       52.60
Name: 17942, dtype: float64
U           NaN
V          0.72
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       52.80
Name: 17944, dtype: float64
U           NaN
V           NaN
W           NaN
T         17.14
DIAG      12.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       52.90
Name: 17945, dtype: float64
U         -0.18
V         -1.28
W          0.12
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       14.30
Name: 18159, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       6.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       46.0
Sec       14.4
Name: 18160, dtype: float64
U           NaN
V          2.77
W           NaN
T         10.89
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       17.50
Name: 18191, dtype: float64
U           NaN
V          2.90
W           NaN
T         68.61
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       18.20
Name: 18198, dtype: float64
U         -0.0
V         -0.0
W          0.0
T          NaN
DIAG       2.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       46.0
Sec       18.4
Name: 18200, dtype: float64
U           NaN
V          1.89
W           NaN
T         77.50
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       18.50
Name: 18201, dtype: float64
U           NaN
V           NaN
W           NaN
T         27.19
DIAG       6.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       18.70
Name: 18203, dtype: float64
U           NaN
V          6.89
W           NaN
T          3.98
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       19.10
Name: 18207, dtype: float64
U           NaN
V           NaN
W           NaN
T         10.04
DIAG      12.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       31.20
Name: 18328, dtype: float64
U           NaN
V           NaN
W           NaN
T         57.39
DIAG      22.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       31.50
Name: 18331, dtype: float64
U          2.61
V          4.52
W         -2.50
T        145.20
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       31.70
Name: 18333, dtype: float64
U         26.93
V          5.86
W           NaN
T        260.28
DIAG      96.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       31.80
Name: 18334, dtype: float64
U         -0.0
V         -0.0
W          0.0
T          NaN
DIAG       2.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       46.0
Sec       31.9
Name: 18335, dtype: float64
U           NaN
V           NaN
W           NaN
T         60.18
DIAG       6.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       32.10
Name: 18337, dtype: float64
A4
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       46.0
Sec       17.4
Name: 18190, dtype: float64
U           NaN
V          6.73
W           NaN
T          8.34
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       29.70
Name: 18313, dtype: float64
U         36.18
V           NaN
W           NaN
T           NaN
DIAG      26.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       36.30
Name: 18379, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       46.0
Sec       42.1
Name: 18437, dtype: float64

B1
B2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       15.1
Name: 16367, dtype: float64
U           NaN
V           NaN
W        -12.17
T           NaN
DIAG      62.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       15.20
Name: 16368, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       15.4
Name: 16370, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       33.1
Name: 16547, dtype: float64
U           NaN
V          0.67
W           NaN
T         54.57
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       36.60
Name: 16582, dtype: float64
U           NaN
V          2.04
W           NaN
T          6.67
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       40.50
Name: 16621, dtype: float64
U         -0.00
V         -0.43
W         -0.34
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       40.90
Name: 16625, dtype: float64
U         -2.0
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       52.1
Name: 16737, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       44.0
Sec        3.2
Name: 16848, dtype: float64
U           NaN
V           NaN
W           NaN
T         10.46
DIAG      12.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       44.00
Sec        4.20
Name: 16858, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       44.0
Sec        8.2
Name: 16898, dtype: float64
B3
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       20.8
Name: 16424, dtype: float64
U           NaN
V          1.08
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       48.80
Name: 16704, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       44.0
Sec       51.9
Name: 17335, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec        8.0
Name: 17496, dtype: float64
U           NaN
V         -0.69
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       13.90
Name: 17555, dtype: float64
U           NaN
V           NaN
W         -5.64
T           NaN
DIAG      62.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       15.10
Name: 17567, dtype: float64
U           NaN
V           NaN
W         39.02
T         43.97
DIAG      26.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       24.70
Name: 17663, dtype: float64
U           NaN
V           NaN
W         -6.13
T           NaN
DIAG      92.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       25.20
Name: 17668, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       25.4
Name: 17670, dtype: float64
U           NaN
V           NaN
W           NaN
T        254.67
DIAG      22.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       26.30
Name: 17679, dtype: float64
U           NaN
V         -0.57
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       26.60
Name: 17682, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       46.0
Sec       13.5
Name: 18151, dtype: float64
B4
U          0.73
V          0.05
W          0.30
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec        1.10
Name: 17427, dtype: float64
U         -1.48
V          0.46
W         -0.44
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       12.00
Name: 17536, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       54.3
Name: 17959, dtype: float64
C1
C2
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       10.2
Name: 16318, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       32.6
Name: 16542, dtype: float64
U           NaN
V           NaN
W           NaN
T         77.93
DIAG      22.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       35.20
Name: 16568, dtype: float64
U           NaN
V           NaN
W         -3.23
T        196.99
DIAG      86.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       35.30
Name: 16569, dtype: float64
U         -0.74
V          1.29
W          0.71
T        150.79
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       35.40
Name: 16570, dtype: float64
U           NaN
V           NaN
W           NaN
T         73.96
DIAG       6.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       35.50
Name: 16571, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      52.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       35.9
Name: 16575, dtype: float64
U           NaN
V           NaN
W           NaN
T        271.67
DIAG      22.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       36.00
Name: 16576, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       36.1
Name: 16577, dtype: float64
U           NaN
V           NaN
W           NaN
T        244.36
DIAG       6.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       36.20
Name: 16578, dtype: float64
U          3.16
V          0.49
W          1.12
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       36.30
Name: 16579, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       59.8
Name: 16814, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       30.4
Name: 17720, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       31.6
Name: 17732, dtype: float64
U           NaN
V          2.93
W           NaN
T          6.93
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       32.70
Name: 17743, dtype: float64
C3
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       43.0
Sec       26.9
Name: 16485, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       44.0
Sec       45.3
Name: 17269, dtype: float64
U          0.23
V         -0.66
W          0.66
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       44.00
Sec       45.40
Name: 17270, dtype: float64
U          NaN
V          NaN
W          NaN
T         13.8
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec        3.9
Name: 17455, dtype: float64
U           NaN
V           NaN
W           NaN
T         50.24
DIAG      22.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec        5.60
Name: 17472, dtype: float64
U          1.63
V          1.87
W         -0.77
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       45.00
Sec       20.20
Name: 17618, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       45.0
Sec       22.9
Name: 17645, dtype: float64

U           NaN
V          0.48
W           NaN
T           NaN
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       11.50
Name: 18131, dtype: float64
U           NaN
V          1.10
W           NaN
T          4.58
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       46.00
Sec       11.60
Name: 18132, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      12.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       46.0
Sec       11.7
Name: 18133, dtype: float64
U           NaN
V          1.94
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       48.00
Sec       42.60
Name: 19642, dtype: float64
U           NaN
V           NaN
W         -5.62
T           NaN
DIAG      86.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       48.00
Sec       44.60
Name: 19662, dtype: float64
C4
U         -3.19
V          1.29
W         -2.55
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       47.00
Sec       22.60
Name: 18842, dtype: float64
U          0.87
V         -0.00
W          0.41
T           NaN
DIAG       2.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       47.00
Sec       45.00
Name: 19066, dtype: float64
D1
D2
U           NaN
V         -0.22
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       35.00
Name: 16566, dtype: float64
U           NaN
V          0.69
W           NaN
T           NaN
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       43.00
Sec       37.60
Name: 16592, dtype: float64
D3
U           NaN
V          0.58
W           NaN
T          8.35
DIAG      82.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       49.00
Sec        2.50
Name: 19841, dtype: float64
D4
U          NaN
V          NaN
W          NaN
T          NaN
DIAG      22.0
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       48.0
Sec       33.7
Name: 19553, dtype: float64
U           NaN
V         -1.12
W           NaN
T          6.07
DIAG      42.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       49.00
Sec        2.70
Name: 19843, dtype: float64
U        -37.77
V           NaN
W           NaN
T          4.70
DIAG      26.00
YYYY    2018.00
MM         3.00
DD        17.00
Hr        12.00
Min       51.00
Sec       54.50
Name: 21561, dtype: float64
U          NaN
V          NaN
W          NaN
T          NaN
DIAG       NaN
YYYY    2018.0
MM         3.0
DD        17.0
Hr        12.0
Min       51.0
Sec       55.6
Name: 21572, dtype: float64

In [37]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burn-0"
files = ["/TOA5_2879.ts_data.dat",\
             "/TOA5_4390.ts_data.dat","/TOA5_4975.ts_data.dat",\
             "/TOA5_4976.ts_data.dat","/TOA5_10442.ts_data.dat",\
             "/TOA5_11585.ts_data.dat"]

for j in range(1,7):
    print("Burn", j, "--"*40)
    path = p +str(j)
    for i in files:
        df = file_to_df(path, i)
        #t_s = "05-29-2019"
        #t_e = "05-30-2019 "
        #mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
        #df=df.loc[mask]
        #df.between_time("05-20-2019" ,"05-21-2019" )



        print(i,len(df))
        for i in range(1,5):
            lst = list(df["diag_rmy_"+str(i)])
            un_lst = sorted(list(np.unique(lst)))
            x = 0
            
            if len(un_lst) ==2 and un_lst[0] ==-9999 :
                #print("Diag",i,":")
                #print("0%")
                continue
            else:
                if -9999 in un_lst:
                    un_lst.remove(-9999)
                if 0 in un_lst:
                    un_lst.remove(0)
                #print(un_lst)
                for i in un_lst:
                    x+= lst.count(i)
                    if x/len(lst)*100 > .15:
                        print("Diag",i,":")
                        print(x/len(lst)*100,"%")
        print()

Burn 1 --------------------------------------------------------------------------------
/TOA5_2879.ts_data.dat 89981

/TOA5_4390.ts_data.dat 92626

/TOA5_4975.ts_data.dat 114275

/TOA5_4976.ts_data.dat 97049

/TOA5_10442.ts_data.dat 100428

/TOA5_11585.ts_data.dat 90992

Burn 2 --------------------------------------------------------------------------------
/TOA5_2879.ts_data.dat 53459

/TOA5_4390.ts_data.dat 35783

/TOA5_4975.ts_data.dat 47866

/TOA5_4976.ts_data.dat 42110

/TOA5_10442.ts_data.dat 29076

/TOA5_11585.ts_data.dat 34718

Burn 3 --------------------------------------------------------------------------------
/TOA5_2879.ts_data.dat 81061

/TOA5_4390.ts_data.dat 67425

/TOA5_4975.ts_data.dat 81702

/TOA5_4976.ts_data.dat 53318

/TOA5_10442.ts_data.dat 55912

/TOA5_11585.ts_data.dat 67470

Burn 4 --------------------------------------------------------------------------------
/TOA5_2879.ts_data.dat 63403

/TOA5_4390.ts_data.dat 62986

/TOA5_4975.ts_data.dat 74341

/TOA5_4976.ts_data.dat 81910

/TOA5_10442.ts_data.dat 60945

/TOA5_11585.ts_data.dat 65077

Burn 5 --------------------------------------------------------------------------------
/TOA5_2879.ts_data.dat 28478

/TOA5_4390.ts_data.dat 57947

/TOA5_4975.ts_data.dat 41963

/TOA5_4976.ts_data.dat 42129

/TOA5_10442.ts_data.dat 26136

/TOA5_11585.ts_data.dat 26993

Burn 6 --------------------------------------------------------------------------------
/TOA5_2879.ts_data.dat 55241

/TOA5_4390.ts_data.dat 51974

/TOA5_4975.ts_data.dat 37593

/TOA5_4976.ts_data.dat 35223

/TOA5_10442.ts_data.dat 53306

/TOA5_11585.ts_data.dat 54147

In [49]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burn-"
files = ["TOA5_4975.ts_data.dat","TOA5_10442.ts_data.dat",\
         "TOA5_4390.ts_data.dat","TOA5_11584.ts_data.dat"]
rang = [7,8]
for j in rang:
    print("Burn", j, "--"*40)
    path = p +f'{j:02}'+"/"
    for i in files:
        df = file_to_df(path, i)
        #t_s = "05-29-2019"
        #t_e = "05-30-2019 "
        #mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
        #df=df.loc[mask]
        #df.between_time("05-20-2019" ,"05-21-2019" )



        print(i,len(df))
        for a in range(1,5):
            lst = list(df["diag_rmy_"+str(a)])
            un_lst = sorted(list(np.unique(lst)))
            x = 0
            if len(un_lst) ==2 and un_lst[0] ==-9999 :
                #print("Diag",i,":")
                #print("0%")
                continue
            else:
                if -9999 in un_lst:
                    un_lst.remove(-9999)
                if 0 in un_lst:
                    un_lst.remove(0)
                #print(un_lst)
                for k in un_lst:
                    x+= lst.count(k)
                if x/len(lst)*100 > 1:
                    print("Diag",a,":")
                    print(round(x/len(lst)*100,3),"%")
        print()

Burn 7 --------------------------------------------------------------------------------
TOA5_4975.ts_data.dat 52826

TOA5_10442.ts_data.dat 63007
Diag 2 :
6.844 %

TOA5_4390.ts_data.dat 60632

TOA5_11584.ts_data.dat 42283

Burn 8 --------------------------------------------------------------------------------
TOA5_4975.ts_data.dat 59933

TOA5_10442.ts_data.dat 68691
Diag 1 :
1.792 %
Diag 2 :
62.609 %
Diag 3 :
6.599 %

TOA5_4390.ts_data.dat 64421

TOA5_11584.ts_data.dat 45009

In [50]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burn-"
files = ["TOA5_4975.ts_data.dat","TOA5_10442.ts_data.dat",\
         "TOA5_11585.ts_data.dat","TOA5_4390.ts_data.dat"]
rang = [9,13]
for j in rang:
    print("Burn", j, "--"*40)
    path = p +f'{j:02}'+"/"
    for i in files:
        df = file_to_df(path, i)
        #t_s = "05-29-2019"
        #t_e = "05-30-2019 "
        #mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
        #df=df.loc[mask]
        #df.between_time("05-20-2019" ,"05-21-2019" )



        print(i,len(df))
        for a in range(1,5):
            lst = list(df["diag_rmy_"+str(a)])
            un_lst = sorted(list(np.unique(lst)))
            x = 0
            if len(un_lst) ==2 and un_lst[0] ==-9999 :
                #print("Diag",i,":")
                #print("0%")
                continue
            else:
                if -9999 in un_lst:
                    un_lst.remove(-9999)
                if 0 in un_lst:
                    un_lst.remove(0)
                #print(un_lst)
                for k in un_lst:
                    x+= lst.count(k)
                if x/len(lst)*100 > 1:
                    print("Diag",a,":")
                    print(round(x/len(lst)*100,3),"%")
        print()

Burn 9 --------------------------------------------------------------------------------
TOA5_4975.ts_data.dat 73634
Diag 3 :
3.972 %

TOA5_10442.ts_data.dat 48496
Diag 2 :
7.341 %

TOA5_11585.ts_data.dat 47668

TOA5_4390.ts_data.dat 78330

Burn 13 --------------------------------------------------------------------------------
TOA5_4975.ts_data.dat 71049
Diag 3 :
4.013 %

TOA5_10442.ts_data.dat 71178

TOA5_11585.ts_data.dat 70039

TOA5_4390.ts_data.dat 70112

In [45]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burn-"
files = ["TOA5_2879.ts_data.dat",\
             "TOA5_4975.ts_data.dat", "TOA5_4976.ts_data.dat", \
             "TOA5_11585.ts_data.dat"]
rang = [18,19]
for j in rang:
    print("Burn", j, "--"*40)
    path = p +f'{j:02}'+"/"
    for i in files:
        df = file_to_df(path, i)
        #t_s = "05-29-2019"
        #t_e = "05-30-2019 "
        #mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
        #df=df.loc[mask]
        #df.between_time("05-20-2019" ,"05-21-2019" )



        print(i,len(df))
        for a in range(1,5):
            lst = list(df["diag_rmy_"+str(a)])
            un_lst = sorted(list(np.unique(lst)))
            x = 0
            if len(un_lst) ==2 and un_lst[0] ==-9999 :
                #print("Diag",i,":")
                #print("0%")
                continue
            else:
                if -9999 in un_lst:
                    un_lst.remove(-9999)
                if 0 in un_lst:
                    un_lst.remove(0)
                #print(un_lst)
                for k in un_lst:
                    x+= lst.count(k)
                    if x/len(lst)*100 > .1:
                        print("Diag",a,":")
                        print(x/len(lst)*100,"%")

Burn 18 --------------------------------------------------------------------------------
TOA5_2879.ts_data.dat 236689
TOA5_4975.ts_data.dat 238524
TOA5_4976.ts_data.dat 227192
TOA5_11585.ts_data.dat 251627
Burn 19 --------------------------------------------------------------------------------
TOA5_2879.ts_data.dat 111483
TOA5_4975.ts_data.dat 111561
TOA5_4976.ts_data.dat 111391
TOA5_11585.ts_data.dat 111048

In [43]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burn-"
["TOA5_2879.ts_data.dat",\
             "TOA5_3884.ts_data.dat", "TOA5_4390.ts_data.dat",\
             "TOA5_4975.ts_data.dat","TOA5_4976.ts_data.dat",
             "TOA5_10442.ts_data.dat", "TOA5_11584.ts_data.dat",\
             "TOA5_11585.ts_data.dat"]
rang = [11,12]
for j in rang:
    print("Burn", j, "--"*40)
    path = p +f'{j:02}'+"/"
    for i in files:
        df = file_to_df(path, i)
        #t_s = "05-29-2019"
        #t_e = "05-30-2019 "
        #mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
        #df=df.loc[mask]
        #df.between_time("05-20-2019" ,"05-21-2019" )



        print(i,len(df))
        for a in range(1,5):
            lst = list(df["diag_rmy_"+str(a)])
            un_lst = sorted(list(np.unique(lst)))
            x = 0
            if len(un_lst) ==2 and un_lst[0] ==-9999 :
                #print("Diag",i,":")
                #print("0%")
                continue
            else:
                if -9999 in un_lst:
                    un_lst.remove(-9999)
                if 0 in un_lst:
                    un_lst.remove(0)
                #print(un_lst)
                for k in un_lst:
                    x+= lst.count(k)
                    if x/len(lst)*100 > 1:
                        print("Diag",a,":")
                        print(x/len(lst)*100,"%")

Burn 11 --------------------------------------------------------------------------------
TOA5_2879.ts_data.dat 69990
TOA5_3884.ts_data.dat 69563
TOA5_4390.ts_data.dat 76408
TOA5_4975.ts_data.dat 56964
TOA5_4976.ts_data.dat 57475
TOA5_10442.ts_data.dat 68015
TOA5_11584.ts_data.dat 57590
TOA5_11585.ts_data.dat 77394
Burn 12 --------------------------------------------------------------------------------
TOA5_2879.ts_data.dat 86342
TOA5_3884.ts_data.dat 86414
TOA5_4390.ts_data.dat 86275
TOA5_4975.ts_data.dat 86377
TOA5_4976.ts_data.dat 86291
TOA5_10442.ts_data.dat 86577
TOA5_11584.ts_data.dat 86364
TOA5_11585.ts_data.dat 86299

In [24]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burns-20-to-22/"
files =["TOA5_4976_TRUSSA.dat","TOA5_4975.ts_data.dat","TOA5_11585.ts_data.dat",\
            "TOA5_2879.ts_data.dat"]


for i in files:
    df = file_to_df(p, i)
    t_s = "05-20-2019"
    t_e = "05-21-2019 "
    mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
    df=df.loc[mask]



    print(i,len(df))
    for i in range(1,5):
        lst = list(df["diag_rmy_"+str(i)])
        un_lst = sorted(list(np.unique(lst)))
        x = 0
        print("Diag",i,":")
        if len(un_lst) ==2 and un_lst[0] ==-9999 :
            print("0%")
            continue
        else:
            if -9999 in un_lst:
                un_lst.remove(-9999)
            if 0 in un_lst:
                un_lst.remove(0)
            #print(un_lst)
            for i in un_lst:
                x+= lst.count(i)
            print(round(x/len(lst)*100,3),"%")
    print()

TOA5_4976_TRUSSA.dat 180665
Diag 1 :
0.001 %
Diag 2 :
0.048 %
Diag 3 :
0.061 %
Diag 4 :
0%

TOA5_4975.ts_data.dat 180885
Diag 1 :
6.078 %
Diag 2 :
0.09 %
Diag 3 :
0.921 %
Diag 4 :
42.805 %

TOA5_11585.ts_data.dat 181331
Diag 1 :
0.002 %
Diag 2 :
0.072 %
Diag 3 :
3.714 %
Diag 4 :
0.283 %

TOA5_2879.ts_data.dat 181740
Diag 1 :
0.002 %
Diag 2 :
0.039 %
Diag 3 :
0.124 %
Diag 4 :
0.084 %

In [25]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burns-23-to-26/"
files =["TOA5_4976_A.dat","TOA5_4975.ts_data.dat","TOA5_11585.ts_data.dat",\
            "TOA5_2879.ts_data.dat"]


for i in files:
    df = file_to_df(p, i)
    t_s = "05-21-2019"
    t_e = "05-22-2019 "
    mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
    df=df.loc[mask]



    print(i,len(df))
    for i in range(1,5):
        lst = list(df["diag_rmy_"+str(i)])
        un_lst = sorted(list(np.unique(lst)))
        x = 0
        print("Diag",i,":")
        if len(un_lst) ==2 and un_lst[0] ==-9999 :
            print("0%")
            continue
        else:
            if -9999 in un_lst:
                un_lst.remove(-9999)
            if 0 in un_lst:
                un_lst.remove(0)
            #print(un_lst)
            for i in un_lst:
                x+= lst.count(i)
            print(round(x/len(lst)*100,3),"%")
    print()

TOA5_4976_A.dat 266020
Diag 1 :
0.004 %
Diag 2 :
0.038 %
Diag 3 :
0.015 %
Diag 4 :
0%

TOA5_4975.ts_data.dat 261036
Diag 1 :
6.631 %
Diag 2 :
0.079 %
Diag 3 :
6.782 %
Diag 4 :
99.923 %

TOA5_11585.ts_data.dat 252767
Diag 1 :
0.011 %
Diag 2 :
0.067 %
Diag 3 :
10.029 %
Diag 4 :
0.105 %

TOA5_2879.ts_data.dat 254771
Diag 1 :
0.003 %
Diag 2 :
0.04 %
Diag 3 :
0.066 %
Diag 4 :
0.066 %

In [26]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burns-27-to-30/"
files =["TOA5_4976.ts_data.dat","TOA5_4975.ts_data.dat","TOA5_11585.ts_data.dat",\
            "TOA5_2879.ts_data.dat"]


for i in files:
    df = file_to_df(p, i)
    t_s = "05-22-2019"
    t_e = "05-23-2019 "
    mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
    df=df.loc[mask]



    print(i,len(df))
    for i in range(1,5):
        lst = list(df["diag_rmy_"+str(i)])
        un_lst = sorted(list(np.unique(lst)))
        x = 0
        print("Diag",i,":")
        if len(un_lst) ==2 and un_lst[0] ==-9999 :
            print("0%")
            continue
        else:
            if -9999 in un_lst:
                un_lst.remove(-9999)
            if 0 in un_lst:
                un_lst.remove(0)
            #print(un_lst)
            for i in un_lst:
                x+= lst.count(i)
            print(round(x/len(lst)*100,3),"%")
    print()

TOA5_4976.ts_data.dat 251523
Diag 1 :
0.004 %
Diag 2 :
0.024 %
Diag 3 :
0.025 %
Diag 4 :
0%

TOA5_4975.ts_data.dat 242210
Diag 1 :
86.57 %
Diag 2 :
0.14 %
Diag 3 :
99.849 %
Diag 4 :
99.916 %

TOA5_11585.ts_data.dat 234133
Diag 1 :
0.004 %
Diag 2 :
0.024 %
Diag 3 :
99.715 %
Diag 4 :
0.072 %

TOA5_2879.ts_data.dat 222890
Diag 1 :
0.074 %
Diag 2 :
0.057 %
Diag 3 :
0.022 %
Diag 4 :
0.014 %

In [28]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burns-31-to-33/"
files =["TOA5_4976.ts_data.dat","TOA5_4975.ts_data.dat","TOA5_11585.ts_data.dat",\
            "TOA5_2879.ts_data.dat"]


for i in files:
    df = file_to_df(p, i)
    t_s = "05-29-2019"
    t_e = "05-30-2019 "
    mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
    df=df.loc[mask]



    print(i,len(df))
    for i in range(1,5):
        lst = list(df["diag_rmy_"+str(i)])
        un_lst = sorted(list(np.unique(lst)))
        x = 0
        print("Diag",i,":")
        if len(un_lst) ==2 and un_lst[0] ==-9999 :
            print("0%")
            continue
        else:
            if -9999 in un_lst:
                un_lst.remove(-9999)
            if 0 in un_lst:
                un_lst.remove(0)
            #print(un_lst)
            for i in un_lst:
                x+= lst.count(i)
            print(round(x/len(lst)*100,3),"%")
    print()

TOA5_4976.ts_data.dat 280514
Diag 1 :
0.009 %
Diag 2 :
0.012 %
Diag 3 :
0.001 %
Diag 4 :
0%

TOA5_4975.ts_data.dat 280747
Diag 1 :
0.019 %
Diag 2 :
0.02 %
Diag 3 :
99.988 %
Diag 4 :
99.998 %

TOA5_11585.ts_data.dat 278613
Diag 1 :
0.011 %
Diag 2 :
0.019 %
Diag 3 :
0.036 %
Diag 4 :
0.006 %

TOA5_2879.ts_data.dat 279431
Diag 1 :
0.009 %
Diag 2 :
0.016 %
Diag 3 :
0.014 %
Diag 4 :
0.028 %

In [30]:
p = "/home/joey/Desktop/10X10_Truss_SERDP_Burns/Raw-Sonic-TC-Data/SERDP-Burns-34-to-35/"
files =["TOA5_4976.ts_data.dat","TOA5_4975.ts_data.dat","TOA5_11585.ts_data.dat",\
            "TOA5_2879.ts_data.dat"]


for i in files:
    df = file_to_df(p, i)
    t_s = "05-31-2019"
    t_e = "06-01-2019 "
    mask =(df['TIMESTAMP'] > t_s) & (df['TIMESTAMP'] < t_e) 
    df=df.loc[mask]



    print(i,len(df))
    for i in range(1,5):
        lst = list(df["diag_rmy_"+str(i)])
        un_lst = sorted(list(np.unique(lst)))
        x = 0
        print("Diag",i,":")
        if len(un_lst) ==2 and un_lst[0] ==-9999 :
            print("0%")
            continue
        else:
            if -9999 in un_lst:
                un_lst.remove(-9999)
            if 0 in un_lst:
                un_lst.remove(0)
            #print(un_lst)
            for i in un_lst:
                x+= lst.count(i)
            print(round(x/len(lst)*100,3),"%")
    print()

TOA5_4976.ts_data.dat 168851
Diag 1 :
0%
Diag 2 :
0.002 %
Diag 3 :
0%
Diag 4 :
0%

TOA5_4975.ts_data.dat 168615
Diag 1 :
0.001 %
Diag 2 :
0.011 %
Diag 3 :
99.997 %
Diag 4 :
99.995 %

TOA5_11585.ts_data.dat 165904
Diag 1 :
0%
Diag 2 :
0.016 %
Diag 3 :
0.005 %
Diag 4 :
0.018 %

TOA5_2879.ts_data.dat 170209
Diag 1 :
0%
Diag 2 :
0.006 %
Diag 3 :
0.004 %
Diag 4 :
0.032 %